import type { ServiceScope } from "./types.js";

export type ProjectBackend = "projects" | "openrefine_projects" | "none";

export interface AppRegistryEntry {
  appName: string;
  scope: ServiceScope;
  toolUrl: string;
  canonicalHost?: string;
  legacyHosts?: readonly string[];
  marketingUrl: string;
  hubHost: string;
  supportsSavedProjects: boolean;
  projectBackend: ProjectBackend;
}

// Draft coverage for Phase 3A. Review URLs and save-support flags before scope enforcement is enabled.
export const APP_REGISTRY: readonly AppRegistryEntry[] = [
  {
    appName: "rawgraphs",
    scope: "viz",
    toolUrl: "https://rawgraphs.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/rawgraphs/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "kepler-gl",
    scope: "viz",
    toolUrl: "https://kepler-gl.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/kepler-gl/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "keplergl",
    scope: "viz",
    toolUrl: "https://kepler-gl.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/kepler-gl/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "cartogram-japan",
    scope: "viz",
    toolUrl: "https://cartogram-japan.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/cartogram-japan/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "cartogram-prefectures",
    scope: "viz",
    toolUrl: "https://cartogram-prefectures.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/cartogram-prefectures/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "choropleth-japan",
    scope: "viz",
    toolUrl: "https://choropleth-japan.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/choropleth-japan/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "choropleth-prefectures",
    scope: "viz",
    toolUrl: "https://choropleth-prefectures.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/choropleth-prefectures/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "interactive-chart-builder",
    scope: "viz",
    toolUrl: "https://interactive-chart-builder.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/interactive-chart-builder/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "sankeymatic",
    scope: "viz",
    toolUrl: "https://sankeymatic.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/sankeymatic/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "voyager2",
    scope: "viz",
    toolUrl: "https://voyager2.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/voyager2/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "tilegrams",
    scope: "viz",
    toolUrl: "https://tilegrams.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/tilegrams/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "gephi-lite",
    scope: "viz",
    toolUrl: "https://gephi-lite.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/gephi-lite/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "data-illustrator",
    scope: "viz",
    toolUrl: "https://data-illustrator.dataviz.jp/app",
    marketingUrl: "https://www.dataviz.jp/data-illustrator/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "vega-editor",
    scope: "viz",
    toolUrl: "https://vega-editor.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/vega-editor/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "word-cloud",
    scope: "viz",
    toolUrl: "https://word-cloud.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/word-cloud/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "cytoscape",
    scope: "viz",
    toolUrl: "https://cytoscape.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/cytoscape/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "parallel-coordinates",
    scope: "viz",
    toolUrl: "https://parallel-coordinates.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/parallel-coordinates/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "drawing-line-chart",
    scope: "viz",
    toolUrl: "https://drawing-line-chart.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/drawing-line-chart/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "3d-surface-chart",
    scope: "viz",
    toolUrl: "https://3d-surface-chart.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/3d-surface-chart/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "bbts",
    scope: "viz",
    toolUrl: "https://bbts.dataviz.jp/",
    marketingUrl: "https://www.dataviz.jp/bbts/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "bar-chart-filter",
    scope: "viz",
    toolUrl: "https://bar-chart-filter.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/bar-chart-filter/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: true,
    projectBackend: "projects",
  },
  {
    appName: "open-refine",
    scope: "prep",
    toolUrl: "https://open-refine.dataprep.jp",
    canonicalHost: "open-refine.dataprep.jp",
    legacyHosts: ["open-refine.dataviz.jp"],
    marketingUrl: "https://www.dataprep.jp/open-refine/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: true,
    projectBackend: "openrefine_projects",
  },
  {
    appName: "mapshaper",
    scope: "prep",
    toolUrl: "https://mapshaper.dataprep.jp",
    canonicalHost: "mapshaper.dataprep.jp",
    legacyHosts: ["mapshaper.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/mapshaper/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "easings",
    scope: "viz",
    toolUrl: "https://easings.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/easings/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "svg-gradient",
    scope: "viz",
    toolUrl: "https://svg-gradient.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/svg-gradient/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "svg-texture",
    scope: "viz",
    toolUrl: "https://svg-texture.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/svg-texture/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "iwanthue",
    scope: "viz",
    toolUrl: "https://iwanthue.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/iwanthue/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "leonardo",
    scope: "viz",
    toolUrl: "https://leonardo.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/leonardo/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "colorbrewer",
    scope: "viz",
    toolUrl: "https://colorbrewer.dataviz.jp",
    marketingUrl: "https://www.dataviz.jp/colorbrewer/",
    hubHost: "app.dataviz.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "jsoncrack",
    scope: "prep",
    toolUrl: "https://jsoncrack.dataprep.jp",
    canonicalHost: "jsoncrack.dataprep.jp",
    legacyHosts: ["jsoncrack.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/jsoncrack/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "geojson",
    scope: "prep",
    toolUrl: "https://geojson.dataprep.jp",
    canonicalHost: "geojson.dataprep.jp",
    legacyHosts: ["geojson.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/geojson/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "change-character-encoding",
    scope: "prep",
    toolUrl: "https://change-character-encoding.dataprep.jp",
    canonicalHost: "change-character-encoding.dataprep.jp",
    legacyHosts: ["change-character-encoding.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/change-character-encoding/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "tabula-pdf",
    scope: "prep",
    toolUrl: "https://tabula-pdf.dataprep.jp",
    canonicalHost: "tabula-pdf.dataprep.jp",
    legacyHosts: ["tabula-pdf.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/tabula-pdf/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "text-entity",
    scope: "prep",
    toolUrl: "https://text-entity.dataprep.jp",
    canonicalHost: "text-entity.dataprep.jp",
    legacyHosts: ["text-entity.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/text-entity/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "aozora-furigana",
    scope: "prep",
    toolUrl: "https://aozora-furigana.dataprep.jp",
    canonicalHost: "aozora-furigana.dataprep.jp",
    legacyHosts: ["aozora-furigana.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/aozora-furigana/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "geo-data-merger",
    scope: "prep",
    toolUrl: "https://geo-data-merger.dataprep.jp",
    canonicalHost: "geo-data-merger.dataprep.jp",
    legacyHosts: ["geo-data-merger.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/geo-data-merger/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "gtfs-to-network",
    scope: "prep",
    toolUrl: "https://gtfs-to-network.dataprep.jp",
    canonicalHost: "gtfs-to-network.dataprep.jp",
    legacyHosts: ["gtfs-to-network.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/gtfs-to-network/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "classic-mapbox-styles",
    scope: "prep",
    toolUrl: "https://classic-mapbox-styles.dataprep.jp",
    canonicalHost: "classic-mapbox-styles.dataprep.jp",
    legacyHosts: ["classic-mapbox-styles.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/classic-mapbox-styles/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "geojson-and-svg",
    scope: "prep",
    toolUrl: "https://geojson-and-svg.dataprep.jp",
    canonicalHost: "geojson-and-svg.dataprep.jp",
    legacyHosts: ["geojson-and-svg.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/geojson-and-svg/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "latlon-formatter",
    scope: "prep",
    toolUrl: "https://latlon-formatter.dataprep.jp",
    canonicalHost: "latlon-formatter.dataprep.jp",
    legacyHosts: ["latlon-formatter.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/latlon-formatter/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "transform-coordinates",
    scope: "prep",
    toolUrl: "https://transform-coordinates.dataprep.jp",
    canonicalHost: "transform-coordinates.dataprep.jp",
    legacyHosts: ["transform-coordinates.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/transform-coordinates/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "address-to-latlon",
    scope: "prep",
    toolUrl: "https://address-to-latlon.dataprep.jp",
    canonicalHost: "address-to-latlon.dataprep.jp",
    legacyHosts: ["address-to-latlon.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/address-to-latlon/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "what-the-tile",
    scope: "prep",
    toolUrl: "https://what-the-tile.dataprep.jp",
    canonicalHost: "what-the-tile.dataprep.jp",
    legacyHosts: ["what-the-tile.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/what-the-tile/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "calendar-converter",
    scope: "prep",
    toolUrl: "https://calendar-converter.dataprep.jp",
    canonicalHost: "calendar-converter.dataprep.jp",
    legacyHosts: ["calendar-converter.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/calendar-converter/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
  {
    appName: "turf-buffer",
    scope: "prep",
    toolUrl: "https://turf-buffer.dataprep.jp",
    canonicalHost: "turf-buffer.dataprep.jp",
    legacyHosts: ["turf-buffer.dataviz.jp"],
    marketingUrl: "https://www.dataviz.jp/turf-buffer/",
    hubHost: "app.dataprep.jp",
    supportsSavedProjects: false,
    projectBackend: "none",
  },
] as const;

export function getAppRegistryEntry(appName: string): AppRegistryEntry | null {
  return APP_REGISTRY.find((entry) => entry.appName === appName) ?? null;
}

export function resolveProjectBackendFromApp(
  appName: string | null | undefined,
): ProjectBackend | null {
  if (!appName) {
    return null;
  }
  return getAppRegistryEntry(appName)?.projectBackend ?? null;
}

export function resolveRequiredScopeFromApp(
  appName: string | null | undefined,
): ServiceScope | null {
  if (!appName) {
    return null;
  }
  return getAppRegistryEntry(appName)?.scope ?? null;
}
